djangonautic_ks/urls.py

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/',include('mainpage.urls'), name="mainpage"),
    path('Signup/',views.signup_view, name="Signup"),
    path('Authentication/',views.Authentication_view, name="Authentication"),
    path('Authentication1/',views.Authentication_view1, name="Authentication1"),
    path('Login/',views.login_view,name="Login"),
    
    path('Log/',views.log_view,name="Log"),
    path('homepage/',views.homepage,name="homepage"),
    path('logout/',views.logout_view,name="logout"), 
    path('update1/',views.update1,name="update1"),
    path('',views.homepage,name="homepage"),
]

urlpatterns += staticfiles_urlpatterns()

mainpage/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='mainpage'
urlpatterns = [
	path('',views.mainpage_view,name="mainpage"),
	path('update/',views.update,name="update"),
	path('voice/',views.voice,name="voice"),
	path('recorder/',views.recorder,name="recorder"),
	path('thankyou/',views.thankyou_view,name="thankyou"),
	path('Login_voice/',views.login_voice,name="Login_voice"),	
	path('recorder_temp/',views.recorder_temp,name="recorder_temp")

	]

mainpage/models.py
from django.db import models
from django.contrib.auth.models import User


class KeystrokeDB(models.Model):
    user_id = models.IntegerField(default=-1)
    user_name = models.CharField(max_length=30, default=None)
    sentence_index=models.IntegerField(default=0)
    for i in range(190):
        exec("chr%d_up=models.IntegerField(default=0)" % i)
        exec("chr%d_dn=models.IntegerField(default=0)" % i)

class KeystrokeDB1(models.Model):
    user_id = models.IntegerField(default=-1)
    user_name = models.CharField(max_length=30, default=None)
    sentence_index=models.IntegerField(default=0)
    for i in range(190):
        exec("chr%d_up=models.IntegerField(default=0)" % i)
        exec("chr%d_dn=models.IntegerField(default=0)" % i)


class user_list(models.Model):
	user_name = models.CharField(max_length=30, default=None)
	index = models.IntegerField(default=0)


class ParametersDB(models.Model):
    user_id = models.IntegerField(default=-1)
    user_name = models.CharField(max_length=30, default=None)
    sentence_index=models.IntegerField(default=0)
    char_index = models.IntegerField(default=-1)
    char_1 = models.IntegerField(default=0)
    char_2 = models.IntegerField(default=0)
    DD=models.IntegerField(default=0)
    DU=models.IntegerField(default=0)
    UD=models.IntegerField(default=0)
    UU=models.IntegerField(default=0)
    H1= models.IntegerField(default=0)
    H2= models.IntegerField(default=0)

class ParametersDB1(models.Model):
    user_id = models.IntegerField(default=-1)
    user_name = models.CharField(max_length=30, default=None)
    sentence_index=models.IntegerField(default=0)
    char_index = models.IntegerField(default=-1)
    char_1 = models.IntegerField(default=0)
    char_2 = models.IntegerField(default=0)
    DD=models.IntegerField(default=0)
    DU=models.IntegerField(default=0)
    UD=models.IntegerField(default=0)
    UU=models.IntegerField(default=0)
    H1= models.IntegerField(default=0)
    H2= models.IntegerField(default=0)

class voiceFeatures(models.Model):
    user_id = models.IntegerField(default=-1)
    user_name = models.CharField(max_length=30, default=None)
    frame_index = models.IntegerField(default=-1)
    for i in range(86):
        exec("f%d=models.FloatField(default=0)" % i)
 
class voiceFeatures_temp(models.Model):
    user_id = models.IntegerField(default=-1)
    user_name = models.CharField(max_length=30, default=None)
    frame_index = models.IntegerField(default=-1)
    for i in range(86):
        exec("f%d=models.FloatField(default=0)" % i)

mainpage/views.py
from django.shortcuts import render,redirect
from .models import user_list,KeystrokeDB,ParametersDB,voiceFeatures,voiceFeatures_temp
from django.http import HttpResponse,JsonResponse
import time
import json
import re
import pandas as pd
import pyaudio
import wave
from array import array
from scipy.io import wavfile
import scipy.signal
from scipy.io.wavfile import write 
import numpy as np
import sqlite3
import librosa
import time
from datetime import timedelta as td
from python_speech_features import mfcc
from python_speech_features import logfbank,fbank,ssc
from pyAudioAnalysis import audioFeatureExtraction
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_recall_fscore_support
from channels import Channel

from djangonautic_ks import my_settings

from pydub import AudioSegment
# Create your views here.


sentence=['qwerty']



def mainpage_view(request):

	
	if request.method=='POST':
		#validat

		

		return redirect('thankyou')
	else:
		#print("...................................in mainpage GET index",index)
		#convert_modeltocsv()
		
		return render(request, 'mainpage/mainpage.html',{'data':sentence[0]})
		
def voice(request):
	return render(request, 'voice.html')

def login_voice(request):
	return render(request, 'Login_voice.html')


def thankyou_view(request):
	return render(request,'thankyou.html')






def update(request):
	if request.method=='POST':
		if 'dict' in request.POST:
			time_list= request.POST.get('dict')
			time_list= json.loads(time_list)
			list_index=request.POST.getlist('list_index[]')			
			print(list_index[1])
			username=request.user.username
			Channel('keystroke_update').send({ "time_list1":time_list,"list_index1":list_index,"username1":username})
			return redirect('mainpage:voice')
		else:
			return HttpResponse('fail')


	
'''def update(request):
	i=0
	j=0
	ch_index=0
	time_list={}
	char_list=[]
	print(request.POST)
	if request.method=='POST':

		if 'dict' in request.POST:
			#print(request.POST)
			#print(time_list)
			time_list= request.POST.get('dict')
			time_list= json.loads(time_list)
			list_index=request.POST.getlist('list_index[]')			
			print(list_index[1])

			for d in range(5):
				print(time_list[d])

				username=request.user.username
				name=user_list.objects.get(user_name=str(username))
				userid=name.id
				sentence_index=name.index
				instance=KeystrokeDB.objects.get_or_create(user_name=str(username), user_id=userid, sentence_index=d)
				instance=KeystrokeDB.objects.get(user_name=str(username),user_id=userid, sentence_index=d)

				
				list_index1=int(list_index[d])
				key_list = list(time_list[d].keys())
				for i in range (0, list_index1):
					key_split1=re.split('[0-9]+',key_list[i])
					#print(key_split1)
					if(key_split1[2]=='dn'):
						if(key_split1[1]=='Backspace'):
							char_list.append(8)
						elif(key_split1[1]=='Shift'):
							char_list.append(16)
						elif(key_split1[1]=="CapsLock"):
							char_list.append(20)
						elif(key_split1[1]=="Tab"):
							char_list.append(9)
						elif(key_split1[1]=="Control"):
							char_list.append(17)
						elif(key_split1[1]=="Alt"):
							char_list.append(18)

						elif(key_split1[1]=='ArrowLeft'):
							char_list.append(37)
						elif(key_split1[1]=='ArrowRight'):
							char_list.append(39)
						elif(key_split1[1]=='Enter'):
							char_list.append(13)
						else:
							char_list.append(ord(key_split1[1]))

						#print('in down',key_split1[1])
						#print('in down if',key_split1[1])
						temp=time_list[d][key_list[i]]
						exec("instance.chr%d_dn=temp" % ch_index)
						for j in range(i,list_index1):
							key_split2=re.split('[0-9]+',key_list[j])
							if(key_split2[2]=='up'):
							#print('in up',key_split2[1])
								if(key_split1[1] == key_split2[1]):
									exec("instance.chr%d_up= time_list[d][key_list[j]]" % ch_index)
									ch_index=ch_index+1
									break

				instance.save()
				#print(char_list)

				i=0

				print(char_list)
				for i in range (0, ch_index-1):

					parameters=ParametersDB.objects.create(user_name=str(username),user_id=userid, char_index = i, sentence_index=d)
					parameters=ParametersDB.objects.get(user_name=str(username),user_id=userid, char_index = i, sentence_index=d)
					parameters.char_1=char_list[i]
					parameters.char_2= char_list[i+1]
					exec("parameters.DD= instance.chr%d_dn-instance.chr%d_dn" % (i+1,i))
					exec("parameters.UD= instance.chr%d_dn-instance.chr%d_up" % (i+1,i))
					exec("parameters.DU= instance.chr%d_up-instance.chr%d_dn" % (i+1,i))
					exec("parameters.UU= instance.chr%d_up-instance.chr%d_up" % (i+1,i))
					exec("parameters.H1= instance.chr%d_up-instance.chr%d_dn" % (i,i))
					exec("parameters.H2= instance.chr%d_up-instance.chr%d_dn" % (i+1,i+1))
					i=i+1
					parameters.save()
					#print('sentence index...........',sentence_index)
				char_list.clear()
				ch_index=0
		print('done')
		return redirect('mainpage:voice')
	else:
		return HttpResponse('fail')'''



def recorder(request):
	THRESHOLD = 500
	CHUNK_SIZE = 1024
	FORMAT = pyaudio.paInt16
	RATE = 44100
	WAVE_OUTPUT_FILENAME = "file.wav"

	if request.method=='POST':
		audio = pyaudio.PyAudio()
		stream= audio.open(format=FORMAT, channels=1, rate=RATE, input=True, frames_per_buffer=CHUNK_SIZE)
		frames=[]
		for i in range(0, int(RATE/CHUNK_SIZE*15)):
			data=stream.read(1024)
			data_chunk=array('h',data)
			vol=max(data_chunk)
			
			
			frames.append(data)
			
		stream.stop_stream()
		stream.close()
		audio.terminate() 
		waveFile= wave.open(WAVE_OUTPUT_FILENAME,'wb')
		waveFile.setnchannels(1)
		waveFile.setsampwidth(audio.get_sample_size(FORMAT))
		waveFile.setframerate(RATE)
		waveFile.writeframes(b''.join(frames))
		waveFile.close()

		rate, data= wavfile.read("file.wav")
		audio_clip = data/32768
		n_rate, n_data= wavfile.read("file.wav")
		noise_clip = n_data/32768
		output = removeNoise(audio_clip=audio_clip, noise_clip=noise_clip,verbose=True,visual=True)
		chunks = librosa.effects.split(output, top_db=30, frame_length=2048, hop_length=512)
		i=0
		out_chunk=[]
		for i in range (len(chunks)):
			out_chunk.extend(output[chunks[i][0]:chunks[i][1]])
		out_chunk = np.array(out_chunk)
		write("Filtered_audio.wav", rate, out_chunk)
		user_name1=request.user.username
		Channel('featuresExtraction').send(dict(
            username1=user_name1,
        ))
		return HttpResponse('success')

	else:
		return HttpResponse('fail')


def fftnoise(f):
    f = np.array(f, dtype='complex')
    Np = (len(f) - 1) // 2
    phases = np.random.rand(Np) * 2 * np.pi
    phases = np.cos(phases) + 1j * np.sin(phases)
    f[1:Np+1] *= phases
    f[-1:-1-Np:-1] = np.conj(f[1:Np+1])
    return np.fft.ifft(f).real

def band_limited_noise(min_freq, max_freq, samples=1024, samplerate=1):
    freqs = np.abs(np.fft.fftfreq(samples, 1/samplerate))
    f = np.zeros(samples)
    f[np.logical_and(freqs>=min_freq, freqs<=max_freq)] = 1
    return fftnoise(f)
 	
def _stft(y, n_fft, hop_length, win_length):
    return librosa.stft(y=y, n_fft=n_fft, hop_length=hop_length, win_length=win_length)
def _istft(y, hop_length, win_length):
    return librosa.istft(y, hop_length, win_length)
def _amp_to_db(x):
    return librosa.core.amplitude_to_db(x, ref=1.0, amin=1e-20, top_db=80.0)
def _db_to_amp(x,):
    return librosa.core.db_to_amplitude(x,ref=1.0)

def removeNoise(audio_clip, noise_clip, n_grad_freq=2, n_grad_time=4, n_fft=2048, win_length=2048, hop_length=512, n_std_thresh=1.5, prop_decrease=1.0, verbose=False, visual=False):
   
    if verbose: start = time.time()
    # STFT over noise
    noise_stft = _stft(noise_clip, n_fft, hop_length, win_length) 
    noise_stft_db = _amp_to_db(np.abs(noise_stft))# convert to dB
    # Calculate statistics over noise
    mean_freq_noise = np.mean(noise_stft_db, axis =1)
    std_freq_noise = np.std(noise_stft_db, axis =1)
    noise_thresh = mean_freq_noise+std_freq_noise*n_std_thresh
    if verbose: print('STFT on noise:', td(seconds=time.time()-start)); start = time.time()
    # STFT over signal
    if verbose: start = time.time()
    sig_stft = _stft(audio_clip, n_fft, hop_length, win_length)
    sig_stft_db = _amp_to_db(np.abs(sig_stft))
    if verbose: print('STFT on signal:',td(seconds=time.time()-start)); start = time.time()
    # Calculate value to mask dB to
    mask_gain_dB = np.min(_amp_to_db(np.abs(sig_stft)))
    print(noise_thresh, mask_gain_dB)
    # Create a smoothing filter for the mask in time and frequency
    smoothing_filter = np.outer(np.concatenate([np.linspace(0,1,n_grad_freq+1,endpoint=False),np.linspace(1,0,n_grad_freq+2)])[1:-1], 
                       np.concatenate([np.linspace(0,1,n_grad_time+1,endpoint=False),np.linspace(1,0,n_grad_time+2)])[1:-1])
    smoothing_filter = smoothing_filter/np.sum(smoothing_filter)
    # calculate the threshold for each frequency/time bin
    db_thresh = np.repeat(np.reshape(noise_thresh, [1,len(mean_freq_noise)]), np.shape(sig_stft_db)[1], axis = 0).T
    # mask if the signal is above the threshold
    sig_mask = sig_stft_db<db_thresh
    if verbose: print('Masking:', td(seconds=time.time()-start)); start = time.time()
    # convolve the mask with a smoothing filter
    sig_mask = scipy.signal.fftconvolve(sig_mask, smoothing_filter,  mode='same')
    sig_mask = sig_mask*prop_decrease
    if verbose: print('Mask convolution:', td(seconds=time.time()-start)); start = time.time()
    # mask the signal
    sig_stft_db_masked = sig_stft_db *(1-sig_mask) + np.ones(np.shape(mask_gain_dB))*mask_gain_dB*sig_mask # mask real
    sig_imag_masked = np.imag(sig_stft)*(1-sig_mask)

mainpage/templates/mainpage/mainpage.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Mainpage</title>
	<link rel="stylesheet" type="text/css" href="{% static 'mainpage.css' %}" >
	<script src="https://code.jquery.com/jquery-3.1.0.min.js" type="text/javascript">

	</script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class = "full">
	<div class="bg"> </div>



	<form class="log_form"  action="{% url 'logout' %}" method="POST" >
		{% csrf_token %}
		<input class="logout_btn" type="submit" name="logout" value="Logout">

	</form>
	<h2 class="head" id="head"> Type the sentences displayed in text box </h2>


	<form class="my_form" name="my_form" action="{%url 'mainpage:voice'%}">
		{% csrf_token %}

		<div class="box">
		<dl>

		<dt><label class="data" for="user_text">any transition is easier if you believe in yourself and your talent</label></dt>
		</br>
		<dt><textarea class="user_text1" id="user_text1" name="user_text1" style="width:650px;height:25px"  onkeydown="func_down(event)" onkeyup="func_up(event)"  autofocus onpaste="return false"> </textarea></dt>
		<dt><input class="submit_btn1"  id="myBtn1" type="button" name="submit" value="Submit" visibility="hidden"  onclick="submit_func1()" style="visibility:hidden;"></dt>
		<dt><label class="data" for="user_text">it does not matter how slowely you go as long as you do not stop</label></dt>
		</br>
		<dt><textarea class="user_text2" id="user_text2" name="user_text2"  style="width:650px;height:25px;" onkeydown="func_down(event)" onkeyup="func_up(event)"  autofocus onpaste="return false"> </textarea></dt>
		<dt><input class="submit_btn2"  id="myBtn2" type="button" name="submit" value="Submit" visibility="hidden" onclick="submit_func2()" style="visibility:hidden;"></dt>
		<dt><label class="data" for="user_text">we know what we are but know not what we may be</label></dt>
		</br>
		<dt><textarea class="user_text3" id="user_text3" name="user_text3"  style="width:650px;height:25px" onkeydown="func_down(event)" onkeyup="func_up(event)"  autofocus onpaste="return false"> </textarea></dt>
		<dt>
		<input class="submit_btn3"  id="myBtn3" type="button" name="submit" value="Submit" visibility="hidden" onclick="submit_func3()" style="visibility:hidden;"></dt>
		<dt><label class="data" for="user_text">you cant always have a good day but you can always face a bad day with a good attitude</label></dt>
		</br>
		<dt><textarea class="user_text4" id="user_text4" name="user_text4" style="width:650px;height:25px" onkeydown="func_down(event)" onkeyup="func_up(event)"  autofocus onpaste="return false"> </textarea></dt>
		<dt>
		<input class="submit_btn4"  id="myBtn4" type="button" name="submit" value="Submit" visibility="hidden" onclick="submit_func4()" style="visibility:hidden;"></dt>
		<dt><label class="data" for="user_text">the best preparation for tomorrow is doing your best today</label></dt>
		</br>
		<dt><textarea class="user_text5" id="user_text5" name="user_text5"  style="width:650px;height:25px" onkeydown="func_down(event)" onkeyup="func_up(event)"  autofocus onpaste="return false"> </textarea></dt>
		<dt>
		<input class="submit_btn5"  id="myBtn5" type="button" name="submit" value="Submit" visibility="hidden" onclick="submit_func()" style="visibility:hidden;"></dt>
		<dt>
		<input class="submit_btn6"  id="myBtn6" type="submit" name="submit" value="Submit" visibility="hidden" onclick="submit_func6()" style="visibility:hidden;"></dt>
		</dl>
		<dt>
			<p class="inst" id="inst">Press Enter to submit </p>
 		</dt>

	</div>
	</form>




<script type="text/javascript">
	var i_up=0;
	var i_dn=0;
	var list_index=[0,0,0,0,0];
	var sent="{{data}}";
	console.log("..........")
	console.log(sent)
	var x;
	var dict={};
    var dict_array=[];
    var sen_index=0;
    console.log("iniiiiiiiiiiiiiiitialize")
//	milli_sec=d.getMilliSeconds();

	var time_list=[];
	var input_sentence="";
	/////////////////////////////
    element1=document.getElementById("user_text2");
   
    
    element2=document.getElementById("user_text3");
    element3=document.getElementById("user_text4");
    element4=document.getElementById("user_text5");

    element1.disabled=true;
    element2.disabled=true;
    element3.disabled=true;
    element4.disabled=true;
	////////////////////////////


	function func_up(event){

		var d=new Date();
		x=event.key;
		console.log(x);
		console.log("in func up");
		console.log(dict_array[0]);
		console.log("in func up");

//		document.getElementById("demo").innerHTML = i ;


       		dict[i_up+x+1+"up"]=d.getTime();

			console.log(dict);
			i_up=i_up+1;
			list_index[sen_index]=list_index[sen_index]+1;

	}

	function func_down(event){

		var d=new Date();
		x=event.key;
		console.log(x);
		var button_index= sen_index+1

//		document.getElementById("demo").innerHTML = i ;
		if (event.keyCode === 13){

			
			var button_str = "myBtn"+button_index
			document.getElementById(button_str).click();
		}

       	dict[i_dn+x+1+"dn"]=d.getTime();

		i_dn=i_dn+1;
		list_index[sen_index]=list_index[sen_index]+1;
    }

    function submit_func(){
		var text_index = sen_index+1
		var text_str = "user_text"+text_index
		var input_text=document.forms["my_form"][text_str].value;
		console.log(input_text);
		console.log("{{data}}");

		if (input_text.trim()=="the best preparation for tomorrow is doing your best today")
		{ 
			console.log("before");
			console.log(dict_array[0]);
			dict_array.push(dict);
			//console.log(dict_array[sen_index]);
			//console.log(sen_index);
			console.log(dict_array[0]);
            dict={};

            
        	console.log("after empty dict..........")
			console.log(dict_array[0]);
			document.getElementById("myBtn6").click();


			//document.getElementById("text_str").value = input_text;

		}
		else
		{
			alert("Please enter correct sentence");
			dict={};
			list_index[sen_index]=0;
			document.getElementById(text_str).value = "";

		}
    


    }


	function submit_func6(){
			console.log('the timer started>>>>>>>>>>>>')
			let timerInterval
			Swal.fire({
  			title: 'Saving you response',
  			
  			timer: 1000,
  			onBeforeOpen: () => {
    		Swal.showLoading()
    		
  			},
  			onClose: () => {
    		clearInterval(timerInterval)
			}
			}).then((result) => {
			if (
			// Read more about handling dismissals
			result.dismiss === Swal.DismissReason.timer
			) {
			console.log('I was closed by the timer')
			}
			})

			up_data={'dict':JSON.stringify(dict_array), 'list_index':list_index, 'csrfmiddlewaretoken': "{{ csrf_token }}"};
			console.log(up_data);
			console.log("Submitted..............")
			$.ajax({type:'POST',url:"{% url 'mainpage:update' %}", data:up_data, async:false});
			console.log("back")

			

			
	}
	function submit_func1(){
			var text_index = sen_index+1
			var text_str = "user_text"+text_index
			var input_text=document.forms["my_form"][text_str].value;
			console.log(input_text);
			console.log("{{data}}");

			if (input_text.trim()=="any transition is easier if you believe in yourself and your talent")
			{ 
				console.log("before");
				console.log(dict_array[0]);
				dict_array.push(dict);
				//console.log(dict_array[sen_index]);
				//console.log(sen_index);
				console.log(dict_array[0]);

				sen_index=sen_index+1;
				text_index=text_index+1;
				text_str = "user_text"+text_index;

			
                dict={};
                element=document.getElementById(text_str);
                element.disabled=false;

                document.getElementById(text_str).focus();
            	console.log("after empty dict..........")
				console.log(dict_array[0]);

				//document.getElementById("text_str").value = input_text;

			}
			else
			{
				alert("Please enter correct sentence");
				dict={};
				list_index[sen_index]=0;
				document.getElementById(text_str).value = "";

			}
	}

		function submit_func2(){
			var text_index = sen_index+1
			var text_str = "user_text"+text_index
			var input_text=document.forms["my_form"][text_str].value;
			console.log(input_text);
			console.log("{{data}}");

			if (input_text.trim()=="it does not matter how slowely you go as long as you do not stop")
			{ 
				console.log("before");
				console.log(dict_array[0]);
				dict_array.push(dict);
				//console.log(dict_array[sen_index]);
				//console.log(sen_index);
				console.log(dict_array[0]);

				sen_index=sen_index+1;
				text_index=text_index+1;
				text_str = "user_text"+text_index;

			
                dict={};
                element=document.getElementById(text_str);
                element.disabled=false;
                document.getElementById(text_str).focus();
            	console.log("after empty dict..........")
				console.log(dict_array[0]);

				//document.getElementById("text_str").value = input_text;

			}
			else
			{
				alert("Please enter correct sentence");
				dict={};
				list_index[sen_index]=0;
				document.getElementById(text_str).value = "";

			}
	}
	function submit_func3(){
			var text_index = sen_index+1
			var text_str = "user_text"+text_index
			var input_text=document.forms["my_form"][text_str].value;
			console.log(input_text);
			console.log("{{data}}");

			if (input_text.trim()=="we know what we are but know not what we may be")
			{ 
				console.log("before");
				console.log(dict_array[0]);
				dict_array.push(dict);
				//console.log(dict_array[sen_index]);
				//console.log(sen_index);
				console.log(dict_array[0]);

				sen_index=sen_index+1;
				text_index=text_index+1;
				text_str = "user_text"+text_index;

			
                dict={};
                element=document.getElementById(text_str);
                element.disabled=false;
                document.getElementById(text_str).focus();
            	console.log("after empty dict..........")
				console.log(dict_array[0]);

				//document.getElementById("text_str").value = input_text;

			}
			else
			{
				alert("Please enter correct sentence");
				dict={};
				list_index[sen_index]=0;
				document.getElementById(text_str).value = "";

			}
	}
	function submit_func4(){
			var text_index = sen_index+1
			var text_str = "user_text"+text_index
			var input_text=document.forms["my_form"][text_str].value;
			console.log(input_text);
			console.log("{{data}}");

			if (input_text.trim()=="you cant always have a good day but you can always face a bad day with a good attitude")
			{ 
				console.log("before");
				console.log(dict_array[0]);
				dict_array.push(dict);
				//console.log(dict_array[sen_index]);
				//console.log(sen_index);
				console.log(dict_array[0]);

				sen_index=sen_index+1;
				text_index=text_index+1;
				text_str = "user_text"+text_index;

			
                dict={};
                element=document.getElementById(text_str);
                element.disabled=false;
                document.getElementById(text_str).focus();
            	console.log("after empty dict..........")
				console.log(dict_array[0]);

				//document.getElementById("text_str").value = input_text;

			}
			else
			{
				alert("Please enter correct sentence");
				dict={};
				list_index[sen_index]=0;
				document.getElementById(text_str).value = "";

			}
	}



//	function fun(event){
//		x= event.which;
//		var up_data={'x':x};
//		$.post(URL,up_data,function(response){
//			if(response == 'success'){
//				alert('Yes');
//			}
//		else {alert('error');
//			}
//		});

//()==(sent.charAt(i))

</script>
</div>
</body>
</html>